### ISSUE TITLE
On plain kubernetes, host IP is passed as replication address

### ISSUE THREAD

**Issue by jberkus** [zalando/spilo#101]
In a Kube install, for some reason the host IP is passed as the advertised API and replication address for each node.  This, of course, doesn't work:

```
2016-11-06 08:45:23,702 INFO: trying to bootstrap from leader 'patroni_0'
pg_basebackup: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "172.31.42.94" and accepting
        TCP/IP connections on port 5432?
```

I'm frankly not sure how it even has access to the host IP, let alone using it mistakenly.  Will find out.

**Comment by jberkus** [comment]
Oh, and that's not just DNS resolution, it's in the etcd record for the master:

```
{"action":"get","node":{"key":"/service/cluster01/members/patroni_0","value":"{\"api_url\":\"http://172.31.42.94:8008/patroni\",\"xlog_location\":352322472,\"conn_url\":\"postgres://172.31.42.94:5432/postgres\",\"state\":\"running\",\"role\":\"master\"}","expiration":"2016-11-06T19:01:33.636889359Z","ttl":22,"modifiedIndex":18801,"createdIndex":18801}}
```

**Comment by alexeyklyukin** [comment]
Hm, the way we obtain the IP address is rather hacky. On AWS we ask for an local IP (local-ipv4) of an AWS instance, which should, in theory, give us the host IP instead of a pod one.

On GCE, on the other hand, we just do socket.gethostbyname(socket.gethostname()), which should resolve the pod's hostname and get us the pod address. I'm wondering if you are running things on AWS, although you mentioned 'plain kubernetes', which probably means GCE.

What we should probably do instead in Spilo is to read this information from some environment variable if it is present, and set it up in the manifest via {{status.podIP}}. What do you think?

**Comment by jberkus** [comment]
We shouldn't use an IP at all; we should use service dns instead, which will be:

```
{pod_name}.{petset_name}.cluster.local
```

Unfortunately, petset_name needs to be manually input as an ENV; currently there's no downward API for it.

**Comment by CyberDem0n** [comment]
Hi @jberkus, we are also running Kubernetes on AWS and yes, that was a bug in Spilo.
It was resolving AWS node IP by doing http request on http://169.254.169.254 instead of taking pod ip... That was  fixed in https://github.com/zalando/spilo/pull/105
So now it should work everywhere, AWS, GCE and even minikube.

Also please take a look on:
https://github.com/zalando/spilo/pull/105/files#diff-8c54fa1e5677a832585d18f396619701R64
I think it's not really nice to rely on labelSelector for changing service pointing to the master. If for some reason we end up having to masters - service will load-balance across them. And this is totally weird. So I've came up with an idea - directly change Endpoins associated with the master Service. Also I've removed labelSelector from the master Service: https://github.com/zalando/spilo/pull/105/files#diff-d4866e5404aed4fefc681b74a5e13d32R83

We are still setting roles on the pods using callback, because they are useful for example for replica load-balancing.
