### ISSUE TITLE
S3 backups with helm chart

### ISSUE THREAD

**Issue by captjt** [zalando/spilo#184]
I am running Patroni in Kubernetes on AWS and I have been trying to configure backups to S3. Is there a clear way to add in S3 integration with the helm chart? I have attempted forking it and also have added this type of [fix](https://github.com/zalando/spilo/blob/master/kubernetes/spilo_kubernetes_aws.yaml#L17-L24) in. I just want to make sure this is the only clear way to move forward with.

Thanks,
Jordan

**Comment by CyberDem0n** [comment]
For us it works.
I mean we are running Spilo in Kubernetes on AWS and using wal-e for continues archiving to S3.

Do you have kube2iam running in the cluster? It is responsible for proxying iam requests from the pod to instance metadata.

Actually there is another way to achieve it, you can change docker image and use usual AWS credentials (secret key and access key) instead of `--aws-instance-profile` wal-e argument.

**Comment by captjt** [comment]
I appreciate the help @CyberDem0n it seems to be answer I was looking for. Will close this issue 👍 on the quick feedback! Thank you!
