### ISSUE TITLE
Build fails due to pg_repack patch

### ISSUE THREAD

**Issue by stefanhipfel** [zalando/spilo#219]
Hi,

when building the spilo image I get errors when following patch is exec:
curl -sL https://github.com/reorg/pg_repack/pull/171.diff | patch -p1 \

The pull seems to have some merge conflicts. How important is that patch?

Thanks a lot

Stefan

**Comment by CyberDem0n** [comment]
There were some api changes related to the CVE-2018-1058 in postgres and pg_repack just stopped working :(

https://github.com/reorg/pg_repack/pull/171 is an attempt to fix it, that's why I switched to build it from sources, from github.

About three weeks ago this PR was working somehow, but since then there were some commits to the master and now there is a conflict. If you don't need pg_repack, just comment out a few lines.
