### ISSUE TITLE
Using spilo on other CSP

### ISSUE THREAD

**Issue by primeprotest** [zalando/spilo#289]
Hello, 

Can I use Spilo with other CSP's or is this supposed to work only with AWS?

This might seem like a stupid question but I was not able to find any documentation or any mention of this anywhere.

**Comment by Jan-M** [comment]
The Spilo image is not per se coupled to AWS. Some tools like Wal-E or Wal-G might be but I believe they also support other blob storage solutions to ship to.

Otherwise I am not immediately aware of any coupling.

Closing this unless @CyberDem0n has more comments, maybe we could update the readme to reflect.
