### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by birdayz** [zalando/spilo#407]
It would be great to have a release containing& supporting Patroni 1.6.4. Thanks!

**Comment by CyberDem0n** [comment]
We are working on it, but it makes sense to wait till tomorrow, because of postgres minor releases.

**Comment by marcostvz** [comment]
Hi @CyberDem0n, today we tried to upgrade to spilo-12, but it failed due to the bug on multi-lined SPILO_CONFIGURATION env var fixed in https://github.com/zalando/spilo/commit/46fbf78eaef7100188c3dc1a675a27c0b3a63bb5

Are there plans for a new spilo-12 release? (no pressure, I just want to know about timing to organize myself)

Kind regards :)

**Comment by FxKu** [comment]
Included in [1.6-p3](https://github.com/zalando/spilo/releases/tag/1.6-p3)
