### ISSUE TITLE
Q: What's the benefit of compression (COMPRESS=true) with Docker doing compression already?

### ISSUE THREAD

**Issue by gertvdijk** [zalando/spilo#411]
On a Docker push, the image layers are automatically compressed with lzma/xz already¹. Why does Spilo attempt to compress files in the image with the build argument `COMPRESS=true`? It means that the image is now double compressed with no obvious benefit to me.

It slows down the start of my cluster too, having to unpack the spilo image on every container start, especially hurting on slower testing hardware where this is a bottleneck.

I just noticed https://github.com/zalando/spilo/pull/409/commits/6e09ae8c8a55f817ed1293aabb82c8ce44730447 removes the compression for the next release (but not for build.sh locally build images)?

https://github.com/zalando/spilo/blob/84668553b9cda6ba9da199ff3b3fe9fd89cf5aec/postgres-appliance/Dockerfile#L463-L479

<sub>¹ [Issue 1266](https://github.com/moby/moby/issues/1266) suggests that `docker push` already has this since at least 2013.</sub>

**Comment by CyberDem0n** [comment]
Well, it was an attempt to make the image smaller.
In the beginning it worked quite well and the compression ratio was very good.
Later things have changed and due to some heavy dependencies like libllvm, libicu, wal-g, and new postgres versions being added the final compression ratio stopped being good.
Also, the necessity to decompress the tarball didn't allow us to run the container with read-only root filesystem.

So yes, we don't build it with compress argument by default anymore, but if someone still wants it such an option still exists.
The `build.sh` script doesn't add any arguments on its own, so I don't understand this part of your question.

P.S. `registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p104` is already "uncompressed"

**Comment by gertvdijk** [comment]
Thanks for the explanation :)
