### ISSUE TITLE
Custom PostgreSQL extensions

### ISSUE THREAD

**Issue by senthilcodr** [zalando/spilo#444]
Does Spilo support enabling/installing other extensions apart from the ones packaged by default?  A user might want to use an extension which is not widely used and it will be good if Spilo can provide necessary hooks to add it.   

If this is not already supported, are there plans to do so?

**Comment by CyberDem0n** [comment]
The image is build keeping in mind that it should be small as possible and optionally immutable and able to run with read-only root fs.
Postgres extension requires to be installed into a specific place on the filesystem, `/usr/lib/postgresql/*/lib/` and `/usr/share/postgresql/*/`, which are parts of possibly read-only fs.
Depending on how the extension is going to be installed (from packages or source files) it might require installing quite a lot of dependencies in order to compile it. If you are planning to do it during the container start that might take significant time and therefore delay start.

The better way for you is probably building a custom image, either by forking and modifying spilo repository or just by building the new image on top of the existing one.

**Comment by senthilcodr** [comment]
Thanks for the detailed explanation @CyberDem0n.  If the extension is a popular one, would you also suggest adding it and contributing directly to this project as another option?  Or does the size restriction disallow that?

**Comment by CyberDem0n** [comment]
Name it :)

**Comment by senthilcodr** [comment]
I am trying to understand the overall approach that we can follow with extensions rather than any specific extension.
But our immediate requirement is this extension called periods: https://github.com/xocolatl/periods
Do you think we can raise a PR for this?

**Comment by CyberDem0n** [comment]
There are ubuntu/debian packages available, so I don't have any objections.
