### ISSUE TITLE
Is there a way to SET patroni and postgres connect address?

### ISSUE THREAD

**Issue by Nutties93** [zalando/spilo#567]
Seems like the spilo image does allow me to set the IP address for POSTGRES and PATRONI.

**Comment by CyberDem0n** [comment]
It uses either the `ip` from instance metadata (if running in the cloud) or the IP of the docker interface.
If running on K8s it also accepts `POD_IP` environment variable.

More details here: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L378-L413

**Comment by sasadangelo** [comment]
@Nutties93 
In this [commit](https://github.com/zalando/spilo/commit/e3ce5702ee93fb6c2a21e4891e557f9c95acd861) I added (with the help of @CyberDem0n) the following environment variable ```RESTAPI_CONNECT_ADDRESS``` where, for example, I use in the following way in my YAML:
```
        - name: RESTAPI_CONNECT_ADDRESS
          value: "$(POD_NAME).<service name>"
```

where **<service name>** is your service name. On a StatefulSet each Pod is registered in CoreDNS with $(POD_NAME).<service name>.svc.cluster.local and you can reference it as explained above.

In the next weeks, I will add also an environment variable for PostgreSQL so that when you run ```patronictl list``` you can see hostnames instead of IPs. The change is similar so if you want you can implement it by yourself checking my commit.
