### ISSUE TITLE
arm64 architecture support for docker image

### ISSUE THREAD

**Issue by zagr0** [zalando/spilo#618]
Hi 

Do you guys plan to add arm architecture support for the docker image?
This would be really great to have because it will allow us to run postgre workloads on [AWS graviton](https://aws.amazon.com/ec2/graviton/) based instance types

Thanks in advance!

**Comment by zagr0** [comment]
https://github.com/zalando/postgres-operator/issues/1109

**Comment by CyberDem0n** [comment]
Well, it is not that hard to achieve. The only problem is that we don't have CI/CD infrastructure with arm64 support.

**Comment by markszente** [comment]
I think the only problem should be that [WAL-G](https://github.com/wal-g/wal-g) does not currently provide releases for ARM64. You [can](https://github.com/wal-g/wal-g/issues/863) build it for that architecture, though.

**Comment by xiaolin8** [comment]
> 

Hi, did you success? I tried to do the same but failed anyway. thx very much for your help.

**Comment by Rojikku** [comment]
It looks like #664 is supposed to fix this, but I'm unclear on if the prebuilt images exist or not because it is apparently unreasonable difficult to query versions of docker images using hosts without web UIs.
Clarification would be appreciated.
I thought it was running on an arm node of mine at one point, but it's gotten pushed out of the buffer, and currently my arm nodes keep getting `standard_init_linux.go:228: exec user process caused: exec format error` so I assume this is the cause.

**Comment by markszente** [comment]
I did manage to build and run this on my Raspberry Pi cluster.

**Comment by CyberDem0n** [comment]
The image is built/pushed under a different name:
```
registry.opensource.zalan.do/acid/spilo-cdp-arm64-14
```

The current latest tag is `2.1-p213`

**Comment by Rojikku** [comment]
I appreciate you creating it, but if they're not pushed under the same name I can only run it on some of the nodes of my mixed architecture cluster, because it can't automatically download the correct version.

**Comment by CyberDem0n** [comment]
That's what we have. Unfortunately our docker registry doesn't support multiarch.

**Comment by xiaolin8** [comment]
xiaolin8/spilo-12:1.6-p5
