### ISSUE TITLE
[Question]: Is SCOPE-config service really necessary?

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#657]
Hi all,

I would like to ask if the service $SCOPE-config should be declared in my Kubernetes YAML file like [here](https://github.com/sasadangelo/patroni-k8s/blob/eea67f2a484b1283692de3e1e8f441b89efd0c63/kustomize/spilo/iks/spilo.yaml#L178-L188)

I know this service is created to avoid Kubernetes deleting the Endpoint [here](https://github.com/sasadangelo/patroni-k8s/blob/eea67f2a484b1283692de3e1e8f441b89efd0c63/kustomize/spilo/iks/spilo.yaml#L159-L168) in case the user forgot to create a service for it.

But if in my YAML I have something [like this](https://github.com/sasadangelo/patroni-k8s/blob/eea67f2a484b1283692de3e1e8f441b89efd0c63/kustomize/spilo/iks/spilo.yaml#L139-L153) is $SCOPE-config service really required? What happens if I miss it in the YAML file?

I know Patroni/Spilo creates it automatically if the Pod has the [right permissions](https://github.com/sasadangelo/patroni-k8s/blob/eea67f2a484b1283692de3e1e8f441b89efd0c63/kustomize/spilo/iks/spilo.yaml#L190-L264). Now considering I already have a Service with the same name as the Endpoint, what is the risk of not declaring the $SCOPE-config service?

The reason I am asking this is that I need to support Spilo multiple clusters and I am using [Kustomize](https://kustomize.io/) to do this. Kustomize introduces a template-free way to customize application configuration that simplifies the use of off-the-shelf applications.
Thank you in advance for reply.

**Comment by CyberDem0n** [comment]
Patroni is using many different endpoints:
- `$SCOPE` - is used for leader elections and keeps the information about the current leader and cluster LSN
- `$SCOPE-config` - keeps the global cluster configuration, initialization status, and failover history
- `$SCOPE-sync` - keeps the information about synchronous nodes
- `$SCOPE-failover` - if used for manual failover/switchover

If there is no respective SVC created for the endpoint, K8s might remove the endpoint.
For sync and failover it is not a big deal, but for the config EP it turned to be actually a bigger deal.
Patroni is able to restore everything, but failover history. I.e. `patronictl history` will no longer show timestamps.
In order to protect from K8s recycling `$SCOPE-config` ep we create the SVC with exactly the same name.
In case if there is no service, Patroni will also try to create `$SCOPE-config` svc, but it could fail and hence there is a danger that `patronictl history` will no longer show timestamps.

**Comment by sasadangelo** [comment]
Thank you very much. This overview gave me more details about what happens behind the scene.
As said above I am using Kustomize to create multiple variations of my basic configuration, one for each cluster I need to support. My problem is that I use a name suffix for my cluster name and doing that I have a problem with that specific service because the name is altered in $SCOPE-config-namesuffix and I was wondering if I can remove this service in order to not waste time figuring out how to address the problem.

Now it's clear that I have to solve the problem.
Thank you again for your support. I close the issue.
