### ISSUE TITLE
[Enhancement Request] Please make enabling Timescale License (TSL) to docker image as an environment variable

### ISSUE THREAD

**Issue by pratapagiri** [zalando/spilo#698]
Currently, enabling the Timescale License (TSL) would require rebuilding the docker image using the build arg ( TIMESCALEDB_APACHE_ONLY=false). 

Can you please make this as Docker image environment variable (with a default  TIMESCALEDB_APACHE_ONLY=true). This environment variable can be read on the startup and enable/disable TSL based on the setting. This will be very useful option, as we don't have rebuild the image for a particular release. We have seen rebuilding the image will have issues due to changed dependencies (ex: [issue-694](https://github.com/zalando/spilo/issues/694))

I found that Crunchydata Postgres has similar option `timescaledb.license: apache`

Please consider adding this option.

**Comment by pratapagiri** [comment]
Any update on this?

**Comment by CyberDem0n** [comment]
We already explained it many times and our opinion will not change: we will not take responsibility for distributing software with a proprietary license in any form.

**Comment by qeternity** [comment]
@pratapagiri and for anyone else who comes across this, we will be building images with the TSDB license and keep close-ish to the release schedule here. You can find these releases at https://hub.docker.com/repository/docker/zumalabs/spilo-14/

I have had to build with TSDB 2.5.2 because 2.6.0 builds are broken due to a CMake change but I will open an MR shortly.
