### ISSUE TITLE
Reduce PATCH Requests to the API-Server for Database-Pod

### ISSUE THREAD

**Issue by ckotzbauer** [zalando/spilo#722]
Hi,
I figured out, that Patroni/Spilo itself does a lot of PATCH-Requests to the Database-Pod (all 10s). This produces a high load to the API-Server and other cluster-components.

- Which parts of the Pod are changed with these PATCH-Requests?
- Are they important to the (single-node) postgres-cluster?
- Can this interval be changed?

**Comment by CyberDem0n** [comment]
Every 10s (by default) Patroni updates the leader Endpoint or ConfigMap and maybe updates its own Pod. Leader object updates are extremely important.
You need to run hundreds of Patroni clusters in order to produce a noticeable load on the K8s API.

You can change loop_wait/retry_timeout/ttl with `patronictl edit-config`. More details about these options in Patroni docs: https://patroni.readthedocs.io/en/latest/SETTINGS.html
Just keep in mind the condition: `loop_wait + 2*retry_timeout <= ttl`.
I.e., if you increase loop_wait you'll also have to increase ttl, what will impact the failover time.
