### ISSUE TITLE
Providing Patroni with a custom CA bundle

### ISSUE THREAD

**Issue by melnik13** [zalando/spilo#726]
Hello,

I use [zalando/posrgres-operator](https://github.com/zalando/postgres-operator) that utilizes Spilo image.

Is there a way to provide Spilo with a custom CA certificate to be passed to Patroni?

Patroni handles the `PATRONI_KUBERNETES_CACERT` environment variable, but Spilo discards this variable and it's never been passed to Patroni.

Here's the link to the same issue discussed in the [zalando/posrgres-operator](https://github.com/zalando/postgres-operator) repository: https://github.com/zalando/postgres-operator/issues/1877.

Is there some way to make Spilo passing thie CA certificate of Kubernetes API Server to Patroni?

Thank you!

**Comment by CyberDem0n** [comment]
Yeah... Spilo currently discards all Patroni environment variables because it is relying on its own.
The `get_dcs_config()` function should be a bit changed so it handles `KUBERNETES_*` env variables similarly to remaining DCS: https://github.com/zalando/spilo/blob/22c9247cb9c8d226fe16545673bbc6d419f4d07c/postgres-appliance/scripts/configure_spilo.py#L691-L726
