### ISSUE TITLE
Sporadic unbounded disk growth in pgdata folder

### ISSUE THREAD

**Issue by michaeljguarino** [zalando/spilo#783]
We've deployed a fair number of spilo postgres instances and in a rare set, it seems like the pgdata volume will grow inexplicably until full and crashing the db.  Once resized, the instance restarts and vacuums the cruft, dropping disk usage to something like 1-2%.  There's no real explanation based on dataset size for this, and I assume it's due to some weird behavior with postgres internals.

I don't have any good logs/disk data for this at the moment, since the evidence is wiped once the instance was restarted, but if there are any theories we'd like to help get it resolved.

**Comment by michaeljguarino** [comment]
I'd have to get it the next time it happens I think.  What should commands should I run to collect the information you'd need?

**Comment by mmoscher** [comment]
@michaeljguarino we had some similar issue in our tests environments. After a short period of days (3-7), a single instance with a spare set of data and small pvc crashes due to full disk.

The issue was related (IMHO) to the psql archive mode with is enabled default in spilo. Consulting some pvc metrics, we saw a monotonic increase in storage consumption. Even on weekends/holidays where no new data was submitted to the instance.

Disabling archive mode solved the issue for us. However, for production environments this is no valid solution. Since our instances were running in a test environment, we had wal_e/wal_g disabled.

Hope this helps ✌️
