### ISSUE TITLE
Schedule for new release with newer ubuntu version

### ISSUE THREAD

**Issue by DYukun** [zalando/spilo#840]
Our org is using spilo in our project. Our vulnerability system found that there are new high priority vulnerability published by ubuntu:
- https://ubuntu.com/security/CVE-2023-0286

We'd like to report this issue and ask if there is any planning of newer release which will cover this vulnerability fix.

Thanks!

**Comment by hughcapet** [comment]
Hello! Thank you for pointing to this issue.

The new Spilo release work is postponed until the upcoming bugfix Patroni release is out (end of this week/beginning of the next week). After that, we will need to test it all locally for about a week to consider it stable and then create the new Spilo release tag.

With all that being said, you don't necessarily need the release to use the Spilo image where this issue is covered. If you build your own image from the current state of mater branch, it will install openssl 3.0.2-0ubuntu1.8, which, as far as I understand, is stated to address this cve.

**Comment by DYukun** [comment]
Thanks! we resovled this by rebuilt with latest base image.
